name: Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on: [push]

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.7.0 # Change to your desired Node.js version

      - name: Install dependencies
        run: npm install
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: build project
        run: npm run build

      - name: copy json files
        run: cp -rf *.json build/

      - name: cd into build folder
        run: cd build

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN_FOUNDO_SERVER }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN_FOUNDO_SERVER }}
      
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN_FOUNDO_SERVER }}
